// Background history-engine regressions plus shared encryption/dictionary checks.
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {emptyCase,sampleCase,evaluate,reconcile,reconcileCredit,validateCase,preparationPack,moneyToPaise} from '../archive/domain.js';
import {sealCase,openCase} from '../dist/privacy.js';
import {languages,dictionaries} from '../dist/i18n.js';
test('issuer event conserves cost and quantity in the synthetic case',()=>{const r=evaluate(sampleCase());assert.deepEqual(r.history,{status:'derived',parentQuantity:1000,childQuantity:100,parentCost:'25947000',childCost:'4053000'});assert.equal(BigInt(r.history.parentCost)+BigInt(r.history.childCost),30000000n);assert.equal(r.next,'missing_death');});
test('optional purchase and holding records do not add claim conditions',()=>{const c=sampleCase();c.documents.death=true;c.documents.request=true;c.documents.statement=false;c.history.cost='';const r=evaluate(c);assert.deepEqual(r.missing,[]);assert.equal(r.next,'contactDP');assert.equal(r.history.childCost,null);});
test('history-only flow does not ask for inheritance documents',()=>{const c=sampleCase();c.purpose='history';c.route=emptyCase().route;const r=evaluate(c);assert.equal(r.next,'historyReady');assert.deepEqual(r.missing,[]);assert.equal(preparationPack(c).purpose,'history');});
test('a dispute or unknown nominee cannot enter the supported route',()=>{for(const [k,v] of [['dispute','yes'],['nominee','unknown'],['adult','no'],['single','no'],['domestic','unknown']]){const c=sampleCase();c.route[k]=v;assert.equal(evaluate(c).next,'reviewRoute');assert.equal(evaluate(c).acceptance,'notEstablished');}});
test('cost without a source remains unknown and history requires the holding reference',()=>{const c=sampleCase();c.history.costSource='';assert.equal(reconcile(c.history).childCost,null);c.history.holdingSource='';assert.equal(reconcile(c.history).status,'needsEvidence');});
test('fractional quantities, intervening trades and malformed money do not produce invented results',()=>{const c=sampleCase();c.history.quantity='1001';assert.equal(reconcile(c.history).status,'needsEvidence');c.history.quantity='1000';c.history.noTrades=false;assert.equal(reconcile(c.history).status,'needsEvidence');for(const v of ['-1','1e5','12.999','NaN','<script>'])assert.throws(()=>moneyToPaise(v));});
test('credit requires identity and movement evidence before comparing quantities',()=>{const c=sampleCase();c.credit.quantity='100';assert.equal(reconcileCredit(c).status,'unverified');c.credit.identityMatch=true;c.credit.reference='synthetic-movement-01';assert.equal(reconcileCredit(c).status,'matched');c.credit.quantity='90';assert.deepEqual(reconcileCredit(c),{status:'difference',difference:-10,expected:100,actual:90,basis:'userConfirmedIdentityAndReference',institutionVerified:false});});
test('changing the basis invalidates an earlier credit result',()=>{const c=sampleCase();c.credit={quantity:'100',identityMatch:true,reference:'demo'};assert.equal(reconcileCredit(c).status,'matched');c.history.noTrades=false;assert.equal(reconcileCredit(c).status,'unverified');});
test('saved case schema validates all route gates and strips arbitrary properties',()=>{const c=sampleCase();const restored=validateCase({...c,malicious:'<script>'});assert.equal(restored.malicious,undefined);assert.deepEqual(restored,c);assert.throws(()=>validateCase({...c,route:{...c.route,nominee:'maybe'}}));assert.throws(()=>validateCase({...c,evidence:[{hash:'bad',name:'x',kind:'pdf',pages:1}]}));});
test('summary omits filenames, personal source text and original files',()=>{const c=sampleCase();c.history.holdingSource='PRIVATE NAME ACCOUNT';c.evidence=[{hash:'a'.repeat(64),name:'private-person.pdf',kind:'pdf',pages:2}];const p=JSON.stringify(preparationPack(c));assert.ok(!p.includes('PRIVATE NAME ACCOUNT'));assert.ok(!p.includes('private-person.pdf'));assert.ok(p.includes('notEstablished'));});
test('encryption round trip, wrong password and ciphertext alteration',async()=>{const c=sampleCase(),password='correct horse battery staple';const envelope=await sealCase(c,password);assert.ok(!envelope.includes('300000'));assert.deepEqual(await openCase(envelope,password),c);await assert.rejects(openCase(envelope,'wrong password is long enough'),/cannotUnlock/);const e=JSON.parse(envelope);e.ciphertext=(e.ciphertext[0]==='A'?'B':'A')+e.ciphertext.slice(1);await assert.rejects(openCase(JSON.stringify(e),password),/cannotUnlock/);await assert.rejects(sealCase(c,'short'),/passwordShort/);});
test('malicious encryption parameters and oversized input are rejected before decryption',async()=>{await assert.rejects(openCase('x'.repeat(2200000),'valid long password'),/invalidSave/);await assert.rejects(openCase(JSON.stringify({format:'sangyan-encrypted-case',version:1,kdf:'PBKDF2-SHA256',iterations:999999999}),'valid long password'),/invalidSave/);});
test('every selectable language has all interface keys',()=>{const keys=Object.keys(dictionaries.en).sort();for(const [code] of languages){assert.deepEqual(Object.keys(dictionaries[code]??{}).sort(),keys,code);for(const key of keys)assert.equal(typeof dictionaries[code][key],'string',`${code}:${key}`);}});
