// One practical browser smoke. Use synthetic inputs on the existing preview.
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
const {chromium}=await import(process.env.SANGYAN_PLAYWRIGHT_MODULE||process.env.VIRASAT_PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,channel:'chrome'}),context=await browser.newContext({viewport:{width:1280,height:900},acceptDownloads:true}),page=await context.newPage();
const errors=[],requests=[],checks=[],check=(name,pass)=>{assert.ok(pass,name);checks.push(name);};
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push({url:r.url(),method:r.method()}));
try{
 await page.goto('http://127.0.0.1:4173/');
 check('first visit contains only language question and six choices',await page.locator('[data-language]').count()===6&&!await page.locator('header').isVisible()&&!await page.locator('footer').isVisible()&&await page.locator('main h1').innerText()==='Which language do you prefer?');
 await page.keyboard.press('Tab');check('language choices work by keyboard',await page.locator('[data-language=en]').evaluate(e=>e===document.activeElement));await page.keyboard.press('Enter');assert.equal(new URL(page.url()).pathname,'/');
 await page.locator('#add').click();await page.locator('input[name=type][value=bank]').check();await page.locator('#account-form [type=submit]').click();await page.locator('#account-form [type=submit]').click();assert.equal(await page.locator('#account-institution').getAttribute('aria-invalid'),'true');assert.ok(await page.locator('#account-institution').evaluate(e=>e===document.activeElement));await page.locator('#account-institution').fill('HDFC Bank');assert.ok(await page.locator('#institution-guidance a').isVisible());await page.locator('#account-institution').fill('HDFC Securities');assert.equal(await page.locator('#institution-guidance a').count(),0);await page.locator('#account-institution').fill('Synthetic Bank');await page.locator('#home-button').click();await page.locator('#continue-draft').click();check('Home exits setup and resumes the unfinished question',await page.locator('#account-institution').inputValue()==='Synthetic Bank');await page.locator('#account-form [type=submit]').click();assert.equal(await page.locator('#account-extra').count(),0);assert.equal(await page.locator('input[type=date],select[name=recordKind]').count(),0);await page.locator('input[name=nomination][value=missing]').check();await page.locator('#account-form [type=submit]').click();assert.ok(await page.locator('#submit-request').isVisible());
 await page.locator('#edit-account').click();await page.locator('#account-extra summary').click();await page.locator('#account-label').fill('Family savings');await page.locator('#account-owner').fill('Parent');await page.locator('#account-nomineeNote').fill('Spouse / test nickname');await page.locator('#account-last4').fill('1234');
 const native={en:'English',hi:'हिन्दी',bn:'বাংলা',mr:'मराठी',ta:'தமிழ்',ur:'اردو'};await page.locator('#account-nomineeNote').evaluate(e=>{e.focus();e.setSelectionRange(2,6);});
 for(const code of ['hi','bn','mr','ta','ur','en']){await page.locator('#language').selectOption(code);assert.equal(new URL(page.url()).pathname,'/');assert.equal(await page.locator('#language option:checked').innerText(),native[code]);assert.equal(await page.locator('html').getAttribute('dir'),'ltr');assert.equal(await page.locator('h1').evaluate(e=>getComputedStyle(e).textAlign),'left');if(code==='ur'){assert.equal(await page.locator('h1 bdi').getAttribute('dir'),'rtl');assert.equal(await page.locator('#account-nomineeNote').evaluate(e=>getComputedStyle(e).textAlign),'left');}assert.equal(await page.locator('#account-nomineeNote').inputValue(),'Spouse / test nickname');assert.ok(await page.locator('#account-extra').evaluate(e=>e.open));}
 check('native languages preserve root URL, drafts and left-aligned layout with inline Urdu text',await page.locator('#account-last4').inputValue()==='1234');await page.locator('#account-form [type=submit]').click();assert.equal(await page.locator('.task-checklist li').count(),3);assert.ok(await page.locator('.task-checklist').innerText().then(x=>x.includes('receipt alone')));
 await page.locator('#submit-request').click();await page.locator('#account-recordNote').fill('<script>window.injected=true</script>');await page.locator('#progress-form [type=submit]').click();check('submitted request remains awaiting confirmation',await page.locator('.status-pill').innerText()==='Awaiting confirmation');check('private record note renders as text',await page.evaluate(()=>!window.injected)&&await page.locator('.record-review').innerText().then(x=>x.includes('<script>')));
 await page.locator('#confirm-record').click();await page.locator('#progress-form [type=submit]').click();assert.equal(await page.locator('#record-statement').getAttribute('aria-invalid'),'true');assert.ok(await page.locator('#record-statement').evaluate(e=>e===document.activeElement));await page.locator('#record-statement').check();await page.locator('#account-confirmationOn-day').fill('31');await page.locator('#account-confirmationOn-month').fill('02');await page.locator('#account-confirmationOn-year').fill('2026');await page.locator('[name=confirmationChecked]').check();await page.locator('#progress-form [type=submit]').click();assert.equal(await page.locator('#account-confirmationOn-day').getAttribute('aria-invalid'),'true');assert.ok(await page.locator('#account-confirmationOn-error').isVisible());const now=new Date();await page.locator('#account-confirmationOn-day').fill(String(now.getDate()));await page.locator('#account-confirmationOn-month').fill(String(now.getMonth()+1));await page.locator('#account-confirmationOn-year').fill(String(now.getFullYear()));await page.locator('#language').selectOption('ur');assert.equal(await page.locator('#account-confirmationOn-day').inputValue(),String(now.getDate()));await page.locator('#language').selectOption('en');await page.locator('#progress-form [type=submit]').click();check('confirmation uses explained record radios and real dates with inline errors',await page.locator('.status-pill').innerText()==='Checked in a record');
 await page.locator('#home-button').click();await page.locator('#summary').click();const sd=page.waitForEvent('download');await page.locator('#export').click();const summary=await sd;await summary.saveAs('/private/tmp/virasat-smoke-summary.json');const s=JSON.parse(await readFile('/private/tmp/virasat-smoke-summary.json','utf8'));check('summary retains chosen family/nominee labels and omits private record notes',s.accounts[0].nomineeNote==='Spouse / test nickname'&&!JSON.stringify(s).includes('<script>'));
 await page.locator('#home-button').click();await page.locator('#save').click();await page.locator('#password').fill('strong synthetic password 2026');const vd=page.waitForEvent('download');await page.locator('#vault-form [type=submit]').click();const encrypted=await vd;await encrypted.saveAs('/private/tmp/virasat-smoke.virasat');check('saved list is encrypted',!(await readFile('/private/tmp/virasat-smoke.virasat','utf8')).includes('Synthetic Bank'));
 page.once('dialog',d=>d.accept());await page.locator('#clear').click();await page.locator('#resume').click();await page.locator('#saved-file').setInputFiles('/private/tmp/virasat-smoke.virasat');await page.locator('#password').fill('wrong long password 2026');await page.locator('#vault-form [type=submit]').click();await page.locator('#vault-status').filter({hasText:'could not be verified'}).waitFor();await page.locator('#password').fill('strong synthetic password 2026');await page.locator('#vault-form [type=submit]').click();await page.locator('[data-account]').first().waitFor();check('encrypted resume recovers confirmation and nominee notes',await page.locator('.status-pill').first().innerText()==='Checked in a record');
 await page.locator('#language').selectOption('mr');await page.locator('#access-toggle').click();await page.locator('#read-aloud').click();await page.locator('#language').selectOption('en');assert.equal(await page.locator('#voice-status').innerText(),'');await page.locator('#text-up').click();await page.locator('#contrast').check();await page.locator('#reduce-motion').check();await page.locator('#language').selectOption('ur');check('language changes retain accessibility settings',await page.locator('#text-level').innerText()==='110%'&&await page.locator('html').evaluate(e=>e.classList.contains('high-contrast')&&e.classList.contains('no-motion')));await page.keyboard.press('Escape');check('accessibility popover closes and restores focus',await page.locator('#access-panel').isHidden()&&await page.locator('#access-toggle').evaluate(e=>e===document.activeElement));
 await page.setViewportSize({width:320,height:800});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('#access-toggle').click();for(let i=0;i<9;i++)await page.locator('#text-up').click();check('Urdu at 200% text reflows at 320px',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.screenshot({path:'/private/tmp/virasat-smoke-urdu-large.png',fullPage:true});
 check('no persistent case storage or document submission requests',requests.every(r=>r.method==='GET'&&new URL(r.url).hostname==='127.0.0.1')&&await page.evaluate(async()=>localStorage.length===0&&sessionStorage.length===0&&(await indexedDB.databases()).length===0));check('no application runtime errors',errors.length===0);
 const legacy=await context.newPage();await legacy.goto('http://127.0.0.1:4173/hi');check('legacy language entries canonicalize to root without changing language',new URL(legacy.url()).pathname==='/'&&await legacy.locator('html').getAttribute('lang')==='hi');await legacy.close();
 const result={date:new Date().toISOString(),browser:'installed Chrome, headless',profile:'localhost, desktop and 320px viewport, no CPU/network throttle',checks,runtimeErrors:errors,limitations:['Smoke coverage only; not WCAG certification.','Translations await fluent-reader review.','TalkBack/VoiceOver and low-end-device user testing remain pending.','Hosted header enforcement is not measured by this local smoke.']};await writeFile('/private/tmp/virasat-smoke-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await browser.close();}
